### ISSUE TITLE
Feature request: Reload particular skin

### ISSUE THREAD

**Issue by sylae** [SvetlozarValchev/dv-skin-manager-mod#22]
Not sure how feasible this is, but when doing rapid-fire skin editing (i'm incompetent at blender etc, so i edit textures in gimp and then reload to see if it looks okay) it can get tedious to do the whole "ctrl-f10 -> reload all textures -> wait -> reapply skin with radio" shtick.

it'd be neat if there was a comms radio mode (maybe enabled in settings or something?) that when used on a car, reloads the texture for the currently applied skin and then re-applies it.

**Comment by katycat5e** [comment]
I had some thoughts on how to implement this, will def be looking into it.
