### ISSUE TITLE
Hidden wheels and axles don't get reskinned

### ISSUE THREAD

**Issue by pjschinske** [SvetlozarValchev/dv-skin-manager-mod#26]
This mod doesn't seem to reskin any hidden axles and wheels. Normally this isn't an issue, but the Rearranged S282 mod creates hidden axles that should still be reskinned.

For example, if you're using a 2-8-2 wheel arrangement on the S282, the fifth drive wheels are hidden and won't be reskinned. If you then reskin the locomotive, then switch to a 2-10-2 wheel arrangement, the fifth drive wheels might show up with the previous skin.

Naturally, this bug occurs with the leading and trailing axles too.

I could fix this in Rearranged S282 with some kind of harmony patch, but it seems easiest if it's patched in Skin Manager.

It seems like all that needs to change is [this line:](https://github.com/derail-valley-modding/skin-manager/blob/master/SkinManagerMod/SkinManager.cs#L103)
`foreach (var renderer in objectRoot.GetComponentsInChildren<MeshRenderer>())`
into this:
`foreach (var renderer in objectRoot.GetComponentsInChildren<MeshRenderer>(true))`

This bug happens because `Component.GetComponentsInChildren()` does not search inactive GameObjects unless you set the `includeInactive` parameter to `true`.

Would this be a reasonable change?

**Comment by katycat5e** [comment]
Yes this shouldn't cause any issues to implement 👍

**Comment by pjschinske** [comment]
Sounds good, thanks Katycat
